### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。

### ISSUE THREAD

**Issue by loolksama** [mgsweet/Apex-NoRecoil-2021#189]
Traceback (most recent call last):PON: None | RECOGNIZED: False | SUPPORTED: False
  File "C:\Users\Administrator\Desktop\Halo\python\main.py", line 99, in <module>
    active_weapon = read_weapon(weapon_screenshot("one"))
  File "C:\Users\Administrator\Desktop\Halo\python\main.py", line 60, in read_weapon
    text = pytesseract.image_to_string(cv_image)
  File "E:\Python\lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
  File "E:\Python\lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "E:\Python\lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "E:\Python\lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "E:\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by krampus-nuggets** [comment]
@loolksama - There's missing output for this Traceback, please send the full error output.
